apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-forbid
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-forbid
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello World!"; sleep 140
          restartPolicy: OnFailure
