apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-historylimit
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: cronjob-historylimit
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Hello World!"; exit $((RANDOM%2))
          restartPolicy: OnFailure
